# Variables.
ENVIRONMENT             ?=
IMAGE_TAG               ?= latest
REGISTRY_HOST           ?= ghcr.io/utexo-protocol
CURRENT_DATE_TIME       := $(shell date +'%Y-%m-%d')
LATEST_COMMIT           := $(shell git rev-parse --short HEAD)

# Image names.
PARENT_IMAGE      := utexo-bridge-parent
ENCLAVE_IMAGE     := utexo-bridge-enclave
ENCLAVE_DEV_IMAGE := utexo-bridge-enclave-light

# Variables for build.
IMAGE_PARENT_BACKUP      = $(REGISTRY_HOST)/$(PARENT_IMAGE)$(ENVIRONMENT):$(CURRENT_DATE_TIME)-$(LATEST_COMMIT)
IMAGE_PARENT_LATEST      = $(REGISTRY_HOST)/$(PARENT_IMAGE)$(ENVIRONMENT):$(IMAGE_TAG)
IMAGE_ENCLAVE_BACKUP     = $(REGISTRY_HOST)/$(ENCLAVE_IMAGE)$(ENVIRONMENT):$(CURRENT_DATE_TIME)-$(LATEST_COMMIT)
IMAGE_ENCLAVE_LATEST     = $(REGISTRY_HOST)/$(ENCLAVE_IMAGE)$(ENVIRONMENT):$(IMAGE_TAG)
IMAGE_ENCLAVE_DEV_BACKUP = $(REGISTRY_HOST)/$(ENCLAVE_DEV_IMAGE)$(ENVIRONMENT):$(CURRENT_DATE_TIME)-$(LATEST_COMMIT)
IMAGE_ENCLAVE_DEV_LATEST = $(REGISTRY_HOST)/$(ENCLAVE_DEV_IMAGE)$(ENVIRONMENT):$(IMAGE_TAG)
