[package]
name = "utexo-bridge-parent"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "utexo-bridge-parent"
path = "src/main.rs"

[[bin]]
name = "utexo-bridge-parent-cli"
path = "src/bin/cli.rs"

[dependencies]
prost = "0.13"
tonic = "0.12"
tonic-reflection = "0.12"
tokio = { version = "1", features = ["full"] }

clap = { version = "4", features = ["derive"] }

thiserror = "2"
anyhow = "1"

hex = "0.4"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[target.'cfg(target_os = "linux")'.dependencies]
vsock = "0.5"

[build-dependencies]
prost-build = "0.13"
tonic-build = "0.12"

[features]
default = []
vsock = []
