name: "CD Stage"

on:
  push:
    branches: [stage]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  cd:
    uses: ./.github/workflows/cd-reusable.yml
    with:
      stage: stage
      env_suffix: -stage
      force_build: ${{ github.event_name == 'workflow_dispatch' }}
    secrets: inherit
